const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAE:'CHANGE_LANGUAE',

   
   

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL:'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
     //ADMIN
    
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIL: 'FETCH_GENDER_FAIL',
    //
    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FECTCH_POSITION_SUCCESS: 'FECTCH_POSITION_SUCCESS',
    FECTCH_POSITION_FAILS: 'FECTCH_POSITION_FAILS',
    //
    FETCH_ROLES_START: 'FETCH_ROLES_START',
    FECTCH_ROLES_SUCCESS: 'FECTCH_ROLES_SUCCESS',
    FECTCH_ROLES_FAILS: 'FECTCH_ROLES_FAILS',
    //
    SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
    SAVE_USER_FAILED: 'SAVE_USER_FAILED',
    //
    FECTCH_ALL_USERS_SUCCESS: 'FECTCH_ALL_USERS_SUCCESS',
    FECTCH_ALL_USERS_FAILS: 'FECTCH_ALL_USERS_FAILS',
    //deleteuser 
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILS:'DELETE_USER_FAILS',
    //load top doctor
    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAILS: 'FETCH_ALL_DOCTOR_FAILS',
    //get all doctor
    FETCH_DOCTOR_SUCCESS: 'FETCH_DOCTOR_SUCCESS',
    FETCH_DOCTOR_FAILS: 'FETCH_DOCTOR_FAILS',
    //
    SAVE_DOCTOR_INFOR_SUCCESS: 'SAVE_DOCTOR_INFOR_SUCCESS',
    SAVE_DOCTOR_INFOR_FAILED: 'SAVE_DOCTOR_INFOR_FAILED',

    
    
    


})

export default actionTypes;